# SPDX-FileCopyrightText: 2026 Jacques Supcik <jacques.supci@hes-so.ch>
#
# SPDX-License-Identifier: MIT
---
- name: Validate system requirements
  assert:
    that:
      - ansible_facts["system"] | lower == 'linux'
      - ansible_facts["service_mgr"] == 'systemd'
    fail_msg: 'This role requires a Linux system with systemd as the service manager.'

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  loop:
    - chromium
    - unclutter
    - xinit
    - xserver-xorg
    - x11-utils
    - x11-xserver-utils

- name: Install X11 configuration file
  ansible.builtin.template:
    src: kiosk-xinit.j2
    dest: /etc/X11/xinit/kiosk-xinit
    mode: '0755'
  when:
    - ansible_facts["system"] | lower == 'linux'

- name: Fix Xwrapper.config for anybody rights
  ansible.builtin.lineinfile:
    path: /etc/X11/Xwrapper.config
    regexp: '^allowed_users='
    line: 'allowed_users=anybody'

- name: Fix Xwrapper.config for root rights
  ansible.builtin.lineinfile:
    path: /etc/X11/Xwrapper.config
    regexp: '^needs_root_rights='
    line: 'needs_root_rights=yes'

- name: Install systemd service unit
  ansible.builtin.template:
    src: kiosk.service.j2
    dest: /etc/systemd/system/kiosk.service
    mode: '0644'
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'
  notify:
    - Reload systemd
    - Restart kiosk

- name: Ensure kiosk service is enabled and started
  ansible.builtin.systemd:
    name: kiosk
    enabled: true
    state: started
    daemon_reload: true
  when:
    - ansible_facts["system"] | lower == 'linux'
    - ansible_facts["service_mgr"] == 'systemd'

- name: Set kernel video mode
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^#?video='
    line: 'video={{ kiosk_kernel_video }}'
